import React from "react";
import QRCode from "react-qr-code";

function TransferPage() {
  return (
    <QRCode value="I was raised in a house without soda or sugary drinks other than one glass of fruit juice at breakfast (we were not allowed to drink anything but water and milk other than that). I used to hate the entire concept of sparkling water. I thought it just created waste and costs money.  I also hate the taste.  But,  then I got married,  and my husband really struggles with taking in liquid calories, and is constantly dehydrated.  This year,  as part of his goal to lose weight he has started drinking sparkling water and now I see the value.  He is hydrating without drinking soda,  juice or sugary sports drinks. I was raised in a house without soda or sugary drinks other than one glass of fruit juice at breakfast (we were not allowed to drink anything but water and milk other than that). I used to hate the entire concept of sparkling water. I thought it just created waste and costs money.  I also hate the taste.  But,  then I got married,  and my husband really struggles with taking in liquid calories, and is constantly dehydrated.  This year,  as part of his goal to lose weight he has started drinking sparkling water and now I see the value.  He is hydrating without drinking soda,  juice or sugary sports drinks.I was raised in a house without soda or sugary drinks other than one glass of fruit juice at breakfast (we were not allowed to drink anything but water and milk other than that). I used to hate the entire concept of sparkling water. I thought it just created waste and costs money.  I also hate the taste.  But,  then I got married,  and my husband really struggles with taking in liquid calories, and is constantly dehydrated.  This year,  as part of his goal to lose weight he has started drinking sparkling water and now I see the value.  He is hydrating without drinking soda,  juice or sugary sports drinks.I was raised in a house without soda or sugary drinks other than one glass of fruit juice at breakfast (we were not allowed to drink anything but water and milk other than that). I used to hate the entire concept of sparkling water. I thought it just created waste and costs money.  I also hate the taste.  But,  then I got married,  and my husband really struggles with taking in liquid calories, and is constantly dehydrated.  This year,  as part of his goal to lose weight he has started drinking sparkling water and now I see the value.  He is hydrating without drinking soda,  juice or sugary sports drinks." />
  );
}

export default TransferPage;
